upstream building {
    server web:8000;
}

server {
    listen 80;
    server_name novator-stroy.ru www.novator-stroy.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name novator-stroy.ru www.novator-stroy.ru;

    # Увеличиваем лимит на загрузку файлов до 100MB
    client_max_body_size 100M;

    ssl_certificate /etc/letsencrypt/live/novator-stroy.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/novator-stroy.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://building;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Дополнительные настройки для больших файлов
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}